### ISSUE TITLE
Question about computational resources

### ISSUE THREAD

**Issue by wjn922** [PeihaoChen/RSPNet#1]
Hi,
     Thanks for your wonderful paper and code. I want to know the computational resources of your experiments. 
     1. What and how many GPUs you use?
     2. The training time of pretraining on K400 for 200 epochs.
     3. The training time of finetuning on UCF101, HMDB51, Something-V2, respectively.
     Looking forward to your reply. Thanks.

**Comment by PeihaoChen** [comment]
Thanks for your interest!

1. We use TITAN Xp and V100 GPUs for training.
2. It takes 187h/ 140h/ 166h/ 150h for pretraining our R21D/ ResNet-18/ S3D-G/ C3D models using 6/ 4/ 4/ 4*V100 GPUs, respectively.
3. For C3D model, it takes 0.52h/ 2.27h/ 26.72h for finetuning on UCF101/ HMDB51/ Something-V2 using 4/ 2/ 4*TITAN Xp GPUs, respectively.

**Comment by wjn922** [comment]
Thanks for your kind reply.
