### ISSUE TITLE
The pre-training model of s3d-g model based on Imagenet and dynamics-400 data set?

### ISSUE THREAD

**Issue by LiangSiyv** [PeihaoChen/RSPNet#4]
Where can I download the pre training model of s3d-g model based on Imagenet and dynamics-400 dataset? Or can you upload it to this repository?
请问哪里可以下载到基于ImageNet和Kinetics-400数据集的S3D-G模型的预训练模型？或者请问作者可以上传一下公开吗？

**Comment by PeihaoChen** [comment]
The ImageNet and Kinetics-400 fully supervised pretraining results for S3D-g models are taken from Table 2 in the paper "SpeedNet: Learning the Speediness in Videos". We are not clear how they achieve these results and we have not reproduced them.

**Comment by LiangSiyv** [comment]
Thanks
